### ISSUE TITLE
Content not showing for guests

### ISSUE THREAD

**Issue by GuruMeditation02** [ryancramerdesign/DynamicRoles#4]
Hi, I've come across another issue, but I'm not sure if it's a bug or an intended feature.

Basically I have set up a Dynamic Role purely for guests, but when I add a rule to allow them to view a certain template, they can't. So I'll run through the steps.

1. I uncheck "View Pages" from the basic-page template for all roles.
2. I create a new test page which uses the basic-page template.
3. Viewing this page is forbidden for guests as expected from the front-end.
4. I create a new Dynamic Role roles->Has->guest and template->Equals->basic-page

I would now expect to see the test page without being logged in, but permission is denied. If however I create a new role, let's say General and assign a member to this role and login, I can see the test page and I assume this is because they also automatically have the guest role.

So the issue seems to be when the person isn't logged in, and is purely a guest.

If this is how it's supposed to work, is there a way we can create a Dynamic Role purely for guests? The reason being, I prefer deal with all the permissions for templates etc on one page like can be done with DR. 

Thanks

**Comment by ryancramerdesign** [comment]
Dynamic Roles need an authenticated user before they become useful, so I wouldn't use dynamic roles for non logged-in guest users. There's significant overhead relative to using PW's regular access control, without any benefit. Actually, you don't have to define any access control at all for the scenario of guest users (since this is the default access control state), which enables PW to be more efficient.
